baseURL = 'https://veronicadeleonh.github.io/'
languageCode = 'en-us'
title = 'Verónica De León Hernández'
googleAnalytics = "G-LQZ77WLF6C"
theme = "hugo-PaperModX"


[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
    disableThemeToggle = true
    TocSide = "right"
    DateFormat = "2006"

[params.cover]
    responsiveImages = false
    linkFullImages = true

[params.homeInfoParams]
Content = """**Product Designer <br>with <span class="hover-curiosity">technical curiosity</span> & <span class="hover-systems">systems thinking</span>.**
<span class="subtext">🌿 Interested in <span class="hl">travel</span>, <span class="hl">science</span>, <span class="hl">analog photography</span> and <span class="hl">visual exploration</span>.</span>"""


[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[menu]

[[menu.main]]
name = "Work"
url = "/"
weight = 1
exact = true

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Contact"
url = "https://www.linkedin.com/in/veronicadeleonh/"
weight = 3

[[socialIcons]]
name = "instagram"
url = "<link>"